version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
